# Generated by Django 2.1.2 on 2018-10-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='phone_no',
            field=models.IntegerField(default=10, unique=True),
        ),
    ]
