# Generated by Django 2.1.2 on 2018-10-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0002_auto_20181013_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyExpense.registerdb')),
                ('split', models.BooleanField()),
                ('date', models.DateField()),
                ('list', models.CharField(max_length=10)),
                ('expense', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='email',
            field=models.EmailField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
    ]
