# Generated by Django 2.1.2 on 2018-10-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0004_auto_20181018_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetails',
            new_name='Userdetail',
        ),
    ]
