# Generated by Django 2.1.2 on 2018-10-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0005_auto_20181018_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='expense',
            field=models.IntegerField(),
        ),
    ]
