# Generated by Django 2.1.2 on 2018-10-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0006_auto_20181019_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetail',
            new_name='Userdetails',
        ),
    ]
