# Generated by Django 2.1.2 on 2018-10-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0007_auto_20181019_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='split',
        ),
    ]
