# Generated by Django 2.1.2 on 2018-10-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0008_remove_userdetails_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_no',
            field=models.IntegerField(default=10, unique=True),
        ),
    ]
