# Generated by Django 2.1.2 on 2018-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0009_userdetails_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='friemdsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.IntegerField(default=10),
        ),
    ]
