# Generated by Django 2.1.2 on 2018-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpense', '0010_auto_20181022_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=10)),
                ('friend', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='friemdsList',
        ),
    ]
